/*

Each new term in the fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be...

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms inhe fibonacci sequence whose values do not exceed
four million, find the sum of the eve-valued terms.

*/

#include<iostream>


int main()
{
    int a = 1, b = 2;
    long long sum = 0;
    
    while(b < 4000000) {  
        if((a + b) % 2 == 0) {
            sum += (a + b);
        }
        int temp = a;
        a = b;
        b = temp + b;
    }
    std::cout << sum;
    
    return 0;
}
